[package]
name = "spinne-logger"
description = "Logger for spinne"
license = "MIT"
repository = "https://github.com/tim-richter/spinne"
version = "0.2.3"
edition = "2021"

[dependencies]
colored = "3.0.0"
once_cell = "1"
indicatif = "0"
