[package]
name = "spinne"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_common = "0.37"
swc_ecma_ast = "0.118"
swc_ecma_loader = { version = "0.49", features = ['node']}
swc_ecma_visit = "0.104"

[dev-dependencies]
tempfile = "3.2"
