[package]
name = "spinne"
version = "0.1.0"
description = "spinne is a cli tool that analyzes your project code and finds information about prop usage and other design system analytics."
license = "MIT"
edition = "2021"

[dependencies]
swc_common = { version = "0.37", features = ['tty-emitter']}
swc_ecma_ast = "0.118"
swc_ecma_loader = { version = "0.49", features = ['node']}
swc_ecma_visit = "0.104"
swc_ecma_parser = { version = "0.149", features = ['typescript']}
clap = { version = "4.5.16", features = ["derive"] }
petgraph = { version = "0.6"}

[dev-dependencies]
tempfile = "3.2"