[package]
name = "spinne-html"
description = "HTML representation of component graph for spinne"
license = "MIT"
repository = "https://github.com/tim-richter/spinne"
version = "0.2.3"
edition = "2021"

[dependencies]
serde_json = { workspace = true }

[dev-dependencies]
open = "5"
